version: "3.9"

services:
  app: 
    container_name: fastapi-app
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    volumes:
      - .:/app
    # depends_on: db
    cpus: 0.5
    mem_limit: 512m
    env_file:
      - ./.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    # Important
    ports:
      - 8000:8000
  # pgsql:
  #   image: postgres:13-alpine
  #   volumes:
  #     - ./data/postgres/data:/var/lib/postgresql/data/
  #   ports:
  #     - 35432:5432
  #   env_file:
  #     - ./.env
  # service:
  #   image: nginx
  #   deploy:
  #       resources:
  #           limits:
  #             cpus: 0.50
  #             memory: 512M
  #           reservations:
  #             cpus: 0.25
  #             memory: 128M