version: "3.9"

services:
  app: 
    container_name: fastapi-app
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    # depends_on: db
    cpus: 5
    mem_limit: 8
    env_file:
      - ./.env
    expose:
      - 8000:8000
  pgsql:
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    ports:
      - 35432:5432
    env_file:
      - ./.env